In [68]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import cross_val_score
from sklearn import preprocessing
from sklearn.datasets import make_blobs
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier

In [6]:
data = pd.read_csv("adult.txt", header= None, names=['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'maritalstatus',
'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss',
'hours-per-week', 'native-country', 'income'])
data

,age,workclass,fnlwgt,education,education-num,maritalstatus,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32532,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32533,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32534,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
32535,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
32536,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32537,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
32538,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32541,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K
32542,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K
32543,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32544,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32546,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32547,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32549,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32551,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [20]:
data = data.replace([" ?", "?", " ?"], np.nan)
data = data.dropna()
data

,age,workclass,fnlwgt,education,education-num,maritalstatus,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
30,23,Local-gov,190709,Assoc-acdm,12,Never-married,Protective-serv,Not-in-family,White,Male,0,0,52,United-States,<=50K
31,20,Private,266015,Some-college,10,Never-married,Sales,Own-child,Black,Male,0,0,44,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32526,32,Private,211349,10th,6,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K
32527,22,Private,203715,Some-college,10,Never-married,Adm-clerical,Own-child,White,Male,0,0,40,United-States,<=50K
32528,31,Private,292592,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Wife,White,Female,0,0,40,United-States,<=50K
32529,29,Private,125976,HS-grad,9,Separated,Sales,Unmarried,White,Female,0,0,35,United-States,<=50K
32532,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32533,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32534,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
32535,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
32536,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32537,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
32538,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32543,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32544,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32546,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32547,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32549,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32551,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [76]:
X = data[["age", "education-num", "capital-gain"]]
Y = data["income"]

forest = RandomForestClassifier(n_estimators = 50)
scores = cross_val_score(forest, X, Y, cv=5)
print("Accuracy: %0.4f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.8147 (+/- 0.00)

In [52]:
le = preprocessing.LabelEncoder()
data["sex"] = le.fit_transform(data["sex"])
data["workclass"] = le.fit_transform(data["workclass"])
data["race"] = le.fit_transform(data["race"])
data["native-country"] = le.fit_transform(data["native-country"])
data["maritalstatus"] = le.fit_transform(data["maritalstatus"])
data["relationship"] = le.fit_transform(data["relationship"])
data

,age,workclass,fnlwgt,education,education-num,maritalstatus,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,5,77516,Bachelors,13,4,Adm-clerical,1,4,1,2174,0,40,38,<=50K
1,50,4,83311,Bachelors,13,2,Exec-managerial,0,4,1,0,0,13,38,<=50K
2,38,2,215646,HS-grad,9,0,Handlers-cleaners,1,4,1,0,0,40,38,<=50K
3,53,2,234721,11th,7,2,Handlers-cleaners,0,2,1,0,0,40,38,<=50K
4,28,2,338409,Bachelors,13,2,Prof-specialty,5,2,0,0,0,40,4,<=50K
5,37,2,284582,Masters,14,2,Exec-managerial,5,4,0,0,0,40,38,<=50K
6,49,2,160187,9th,5,3,Other-service,1,2,0,0,0,16,22,<=50K
7,52,4,209642,HS-grad,9,2,Exec-managerial,0,4,1,0,0,45,38,>50K
8,31,2,45781,Masters,14,4,Prof-specialty,1,4,0,14084,0,50,38,>50K
9,42,2,159449,Bachelors,13,2,Exec-managerial,0,4,1,5178,0,40,38,>50K
10,37,2,280464,Some-college,10,2,Exec-managerial,0,2,1,0,0,80,38,>50K
11,30,5,141297,Bachelors,13,2,Prof-specialty,0,1,1,0,0,40,18,>50K
12,23,2,122272,Bachelors,13,4,Adm-clerical,3,4,0,0,0,30,38,<=50K
13,32,2,205019,Assoc-acdm,12,4,Sales,1,2,1,0,0,50,38,<=50K
15,34,2,245487,7th-8th,4,2,Transport-moving,0,0,1,0,0,45,25,<=50K
16,25,4,176756,HS-grad,9,4,Farming-fishing,3,4,1,0,0,35,38,<=50K
17,32,2,186824,HS-grad,9,4,Machine-op-inspct,4,4,1,0,0,40,38,<=50K
18,38,2,28887,11th,7,2,Sales,0,4,1,0,0,50,38,<=50K
19,43,4,292175,Masters,14,0,Exec-managerial,4,4,0,0,0,45,38,>50K
20,40,2,193524,Doctorate,16,2,Prof-specialty,0,4,1,0,0,60,38,>50K
21,54,2,302146,HS-grad,9,5,Other-service,4,2,0,0,0,20,38,<=50K
22,35,0,76845,9th,5,2,Farming-fishing,0,2,1,0,0,40,38,<=50K
23,43,2,117037,11th,7,2,Transport-moving,0,4,1,0,2042,40,38,<=50K
24,59,2,109015,HS-grad,9,0,Tech-support,4,4,0,0,0,40,38,<=50K
25,56,1,216851,Bachelors,13,2,Tech-support,0,4,1,0,0,40,38,>50K
26,19,2,168294,HS-grad,9,4,Craft-repair,3,4,1,0,0,40,38,<=50K
28,39,2,367260,HS-grad,9,0,Exec-managerial,1,4,1,0,0,80,38,<=50K
29,49,2,193366,HS-grad,9,2,Craft-repair,0,4,1,0,0,40,38,<=50K
30,23,1,190709,Assoc-acdm,12,4,Protective-serv,1,4,1,0,0,52,38,<=50K
31,20,2,266015,Some-college,10,4,Sales,3,2,1,0,0,44,38,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32526,32,2,211349,10th,6,2,Transport-moving,0,4,1,0,0,40,38,<=50K
32527,22,2,203715,Some-college,10,4,Adm-clerical,3,4,1,0,0,40,38,<=50K
32528,31,2,292592,HS-grad,9,2,Machine-op-inspct,5,4,0,0,0,40,38,<=50K
32529,29,2,125976,HS-grad,9,5,Sales,4,4,0,0,0,35,38,<=50K
32532,34,2,204461,Doctorate,16,2,Prof-specialty,0,4,1,0,0,60,38,>50K
32533,54,2,337992,Bachelors,13,2,Exec-managerial,0,1,1,0,0,50,23,>50K
32534,37,2,179137,Some-college,10,0,Adm-clerical,4,4,0,0,0,39,38,<=50K
32535,22,2,325033,12th,8,4,Protective-serv,3,2,1,0,0,35,38,<=50K
32536,34,2,160216,Bachelors,13,4,Exec-managerial,1,4,0,0,0,55,38,>50K
32537,30,2,345898,HS-grad,9,4,Craft-repair,1,2,1,0,0,46,38,<=50K
32538,38,2,139180,Bachelors,13,0,Prof-specialty,4,2,0,15020,0,45,38,>50K
32540,45,5,252208,HS-grad,9,5,Adm-clerical,3,4,0,0,0,40,38,<=50K
32543,45,1,119199,Assoc-acdm,12,0,Prof-specialty,4,4,0,0,0,48,38,<=50K
32544,31,2,199655,Masters,14,0,Other-service,1,3,0,0,0,30,38,<=50K
32545,39,1,111499,Assoc-acdm,12,2,Adm-clerical,5,4,0,0,0,20,38,>50K
32546,37,2,198216,Assoc-acdm,12,0,Tech-support,1,4,0,0,0,40,38,<=50K
32547,43,2,260761,HS-grad,9,2,Machine-op-inspct,0,4,1,0,0,40,25,<=50K
32548,65,4,99359,Prof-school,15,4,Prof-specialty,1,4,1,1086,0,60,38,<=50K
32549,43,5,255835,Some-college,10,0,Adm-clerical,2,4,0,0,0,40,38,<=50K
32550,43,4,27242,Some-college,10,2,Craft-repair,0,4,1,0,0,50,38,<=50K
32551,32,2,34066,10th,6,2,Handlers-cleaners,0,0,1,0,0,40,38,<=50K
32552,43,2,84661,Assoc-voc,11,2,Sales,0,4,1,0,0,45,38,<=50K
32553,32,2,116138,Masters,14,4,Tech-support,1,1,1,0,0,11,35,<=50K
32554,53,2,321865,Masters,14,2,Exec-managerial,0,4,1,0,0,40,38,>50K
32555,22,2,310152,Some-college,10,4,Protective-serv,1,4,1,0,0,40,38,<=50K
32556,27,2,257302,Assoc-acdm,12,2,Tech-support,5,4,0,0,0,38,38,<=50K
32557,40,2,154374,HS-grad,9,2,Machine-op-inspct,0,4,1,0,0,40,38,>50K
32558,58,2,151910,HS-grad,9,6,Adm-clerical,4,4,0,0,0,40,38,<=50K
32559,22,2,201490,HS-grad,9,4,Adm-clerical,3,4,1,0,0,20,38,<=50K
32560,52,3,287927,HS-grad,9,2,Exec-managerial,5,4,0,15024,0,40,38,>50K

In [39]:
X = data[["age", "education-num", "sex", "hours-per-week", "capital-gain", "capital-loss"]]
scores = cross_val_score(forest, X, Y, cv = 5)
print("Accuracy: %0.4f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.8193 (+/- 0.00)

In [49]:
X = data[["workclass", "education-num", "capital-gain", "capital-loss"]]
scores = cross_val_score(forest, X, Y, cv = 5)
print("Accuracy: %0.4f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.8286 (+/- 0.00)

In [80]:
X = data[["workclass", "education-num", "capital-gain", "capital-loss", "maritalstatus"]]
scores = cross_val_score(forest, X, Y, cv = 10)
print("Accuracy: %0.4f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.8572 (+/- 0.01)

In [58]:
X = data[["education-num", "capital-gain", "capital-loss", "maritalstatus", "relationship", "race"]]
scores = cross_val_score(forest, X, Y, cv = 5)
print("Accuracy: %0.4f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.8536 (+/- 0.01)

In [78]:
X = data[["education-num", "capital-gain", "capital-loss", "maritalstatus", "sex"]]
scores = cross_val_score(forest, X, Y, cv = 10)
print("Accuracy: %0.4f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.8541 (+/- 0.01)

In [73]:
clf = DecisionTreeClassifier(max_depth= None, min_samples_split= 2)
X = data[["workclass", "education-num", "capital-gain", "capital-loss", "maritalstatus"]]
scores = cross_val_score(clf, X, Y, cv = 10)
print("Accuracy: %0.4f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.8566 (+/- 0.01)

In [77]:
xtc = ExtraTreesClassifier(n_estimators=10, max_depth=None, min_samples_split=2)
X = data[["workclass", "education-num", "capital-gain", "capital-loss", "maritalstatus"]]
scores = cross_val_score(xtc, X, Y, cv = 10)
print("Accuracy: %0.4f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.8540 (+/- 0.01)

In [75]:
abc = AdaBoostClassifier(n_estimators = 20)
X = data[["workclass", "education-num", "capital-gain", "capital-loss", "maritalstatus"]]
scores = cross_val_score(xtc, X, Y, cv = 10)
print("Accuracy: %0.4f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.8539 (+/- 0.01)